#include <cuda_runtime.h>
#include <cublas_v2.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <stdexcept>
#include <string>
#include <vector>

static void ck(cudaError_t e,const char* w){if(e!=cudaSuccess)throw std::runtime_error(std::string(w)+": "+cudaGetErrorString(e));}
static void cb(cublasStatus_t e,const char* w){if(e!=CUBLAS_STATUS_SUCCESS)throw std::runtime_error(std::string(w)+": cublas status "+std::to_string((int)e));}
static std::vector<float> raw(const std::string&p,size_t n){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("open "+p);if((size_t)f.tellg()!=n*4)throw std::runtime_error("size "+p);f.seekg(0);std::vector<float>v(n);f.read((char*)v.data(),n*4);return v;}
static std::vector<float> fvec(const std::string&p,size_t begin,size_t n,int d){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("open "+p);f.seekg((std::streamoff)begin*(d+1)*4);std::vector<float>v(n*(size_t)d);for(size_t i=0;i<n;i++){int x;f.read((char*)&x,4);if(x!=d)throw std::runtime_error("dim");f.read((char*)(v.data()+i*d),d*4);}return v;}
__device__ float wsum(float x){for(int o=16;o;o>>=1)x+=__shfl_down_sync(0xffffffff,x,o);return x;}
__global__ void norms(const float*x,float*out,size_t n,int d){int lane=threadIdx.x&31,wpb=blockDim.x/32,w=threadIdx.x/32;size_t i=(size_t)blockIdx.x*wpb+w;if(i>=n)return;float a=0;for(int j=lane;j<d;j+=32)a=fmaf(x[i*(size_t)d+j],x[i*(size_t)d+j],a);a=wsum(a);if(!lane)out[i]=a;}
__global__ void epilogue(float*c,const float*xnorm,const float*qnorm,const float*tau2,uint32_t*counts,size_t n,int nq){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x,total=n*(size_t)nq;if(i>=total)return;size_t gi=i%n;int qi=(int)(i/n);float d=fmaxf(c[i]+xnorm[gi]+qnorm[qi],0.0f);c[i]=d;if(d<=tau2[qi])atomicAdd(counts+qi,1u);}
struct S{double mean;float min,p50,p95;};static S st(std::vector<float>v){std::sort(v.begin(),v.end());return{std::accumulate(v.begin(),v.end(),0.0)/v.size(),v.front(),v[(size_t)ceil(.5*v.size())-1],v[(size_t)ceil(.95*v.size())-1]};}
int main(int ac,char**av){try{if(ac!=9){std::cerr<<"usage BASE QUERY TAUS BEGIN N Q D REPEATS\n";return 2;}std::string bp=av[1],qp=av[2],tp=av[3];size_t begin=std::stoull(av[4]),n=std::stoull(av[5]);int nq=std::stoi(av[6]),d=std::stoi(av[7]),rep=std::stoi(av[8]);auto hx=fvec(bp,begin,n,d),hq=fvec(qp,0,nq,d),ht=raw(tp,nq*2);std::vector<float>tau2(nq);for(int i=0;i<nq;i++)tau2[i]=ht[2*i]*ht[2*i];float *x,*q,*xn,*qn,*t,*c;uint32_t*cnt;size_t total=n*(size_t)nq;ck(cudaMalloc(&x,hx.size()*4),"mx");ck(cudaMalloc(&q,hq.size()*4),"mq");ck(cudaMalloc(&xn,n*4),"mxn");ck(cudaMalloc(&qn,nq*4),"mqn");ck(cudaMalloc(&t,nq*4),"mt");ck(cudaMalloc(&c,total*4),"mc");ck(cudaMalloc(&cnt,nq*4),"mcnt");ck(cudaMemcpy(x,hx.data(),hx.size()*4,cudaMemcpyHostToDevice),"cx");ck(cudaMemcpy(q,hq.data(),hq.size()*4,cudaMemcpyHostToDevice),"cq");ck(cudaMemcpy(t,tau2.data(),nq*4,cudaMemcpyHostToDevice),"ct");cudaStream_t s;ck(cudaStreamCreate(&s),"stream");int th=256,wpb=8;norms<<<(n+wpb-1)/wpb,th,0,s>>>(x,xn,n,d);norms<<<(nq+wpb-1)/wpb,th,0,s>>>(q,qn,nq,d);ck(cudaStreamSynchronize(s),"norm sync");cublasHandle_t h;cb(cublasCreate(&h),"create");cb(cublasSetStream(h,s),"setstream");cb(cublasSetMathMode(h,CUBLAS_PEDANTIC_MATH),"pedantic");float alpha=-2.f,beta=0.f;auto launch=[&](){ck(cudaMemsetAsync(cnt,0,nq*4,s),"clear");cb(cublasGemmEx(h,CUBLAS_OP_T,CUBLAS_OP_N,(int)n,nq,d,&alpha,x,CUDA_R_32F,d,q,CUDA_R_32F,d,&beta,c,CUDA_R_32F,(int)n,CUBLAS_COMPUTE_32F_PEDANTIC,CUBLAS_GEMM_DEFAULT),"gemm");epilogue<<<(total+255)/256,256,0,s>>>(c,xn,qn,t,cnt,n,nq);};for(int i=0;i<3;i++)launch();ck(cudaStreamSynchronize(s),"warm");cudaEvent_t a,b;ck(cudaEventCreate(&a),"ea");ck(cudaEventCreate(&b),"eb");std::vector<float>times;for(int i=0;i<rep;i++){ck(cudaEventRecord(a,s),"ra");launch();ck(cudaEventRecord(b,s),"rb");ck(cudaEventSynchronize(b),"sb");float ms;ck(cudaEventElapsedTime(&ms,a,b),"el");times.push_back(ms);}launch();ck(cudaStreamSynchronize(s),"final");std::vector<uint32_t>hc(nq);ck(cudaMemcpy(hc.data(),cnt,nq*4,cudaMemcpyDeviceToHost),"cc");if(const char*op=std::getenv("CUBLAS_VALIDATE_OUT")){std::vector<float>ho(total);ck(cudaMemcpy(ho.data(),c,total*4,cudaMemcpyDeviceToHost),"copy validation output");std::ofstream of(op,std::ios::binary);of.write(reinterpret_cast<const char*>(ho.data()),total*4);if(!of)throw std::runtime_error("write validation output");}uint64_t sum=std::accumulate(hc.begin(),hc.end(),uint64_t{0});auto z=st(times);size_t fr,tot;ck(cudaMemGetInfo(&fr,&tot),"mem");std::cout<<std::setprecision(10)<<"{\"n_points\":"<<n<<",\"n_queries\":"<<nq<<",\"dimension\":"<<d<<",\"repeats\":"<<rep<<",\"mean_ms\":"<<z.mean<<",\"min_ms\":"<<z.min<<",\"p50_ms\":"<<z.p50<<",\"p95_ms\":"<<z.p95<<",\"true_within_tau\":"<<sum<<",\"device_used_mib\":"<<(tot-fr)/1048576.0<<",\"math\":\"CUBLAS_COMPUTE_32F_PEDANTIC\"}\n";cublasDestroy(h);return 0;}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<"\n";return 1;}}
